DLS-9710 - Added missing preservingMdc block to mongo calls
hmrc/help-to-save-api pull request #184
Opened 2024-02-01 15:22 UTC by TomRafferty

This PR currently stands to have jenkins run automatically upon changes pushed.

2024-02-01 16:06 UTC, TomRafferty commented
> * There is a bobby warning (builds will be prevented after 31 May 2024) - see the pr builder for details

play to be updated in future tickets

2024-02-01 17:02 UTC, karolina-zaborska submitted a review, later dismissed

2024-02-05 09:58 UTC, johno1985 commented on app/uk/gov/hmrc/helptosaveapi/repo/EligibilityStore.scala
> +    preservingMdc {
not needed as function `doCreateOrUpdate` already has this wrapped

2024-02-05 09:58 UTC, johno1985 requested changes
minor change

2024-02-05 11:06 UTC, johno1985 commented on app/uk/gov/hmrc/helptosaveapi/repo/EligibilityStore.scala
> +    preservingMdc{
this one can go also

2024-02-05 11:06 UTC, johno1985 requested changes
another small change, plus there is a compiler warning about unused import, might be worth doing an optimise import on the project

2024-02-05 11:46 UTC, johno1985 approved these changes

2024-02-06 09:51 UTC, closed without merging